# Generated by Django 4.2.6 on 2023-12-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('DeptNo', models.IntegerField(primary_key=True, serialize=False)),
                ('DName', models.CharField(max_length=50)),
                ('Loc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('EmpNo', models.IntegerField(primary_key=True, serialize=False)),
                ('EName', models.CharField(max_length=30)),
                ('Job', models.CharField(max_length=15)),
                ('Mgr', models.IntegerField()),
                ('Hiredate', models.DateField()),
                ('Sal', models.PositiveIntegerField()),
                ('Commision', models.IntegerField()),
                ('DeptNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dept')),
            ],
        ),
    ]
